FROM node:18-alpine AS base

FROM base AS builder

WORKDIR /app

COPY backend-proxy/package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY backend-proxy /app/

RUN yarn build

RUN yarn install --production --ignore-scripts --prefer-offline --frozen-lockfile

FROM base AS runner

WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/lib ./lib

EXPOSE 4001

ENV PORT 4001

CMD node lib/index.js
