FROM node:18-alpine AS base

# Rebuild the source code only when needed
FROM base AS builder

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY web ./web
COPY shared ./shared
COPY package.json yarn.lock ./
COPY .eslintrc.json ./
COPY .prettierrc.json ./
COPY types ./types
COPY tsconfig.json ./

RUN yarn install --frozen-lockfile --prefer-offline --ignore-scripts

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN --mount=type=secret,id=GRIDLY_VIEW_ID  \
    --mount=type=secret,id=GRIDLY_API_KEY \
    --mount=type=secret,id=BACKEND_URL \
    --mount=type=secret,id=BUILDER_IO_PUBLIC_API_KEY \
    --mount=type=secret,id=MATOMO_URL \
    --mount=type=secret,id=MATOMO_SITE_ID \
    NEXT_PUBLIC_GRIDLY_API_KEY=$(cat /run/secrets/GRIDLY_API_KEY) \
    NEXT_PUBLIC_GRIDLY_VIEW_ID=$(cat /run/secrets/GRIDLY_VIEW_ID) \
    NEXT_PUBLIC_BACKEND_URL=$(cat /run/secrets/BACKEND_URL) \
    NEXT_PUBLIC_BUILDER_API_KEY=$(cat /run/secrets/BUILDER_IO_PUBLIC_API_KEY) \
    NEXT_PUBLIC_MATOMO_URL=$(cat /run/secrets/MATOMO_URL) \
    NEXT_PUBLIC_MATOMO_SITE_ID=$(cat /run/secrets/MATOMO_SITE_ID) \
    yarn --cwd web build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/web/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/web/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "./web/server.js"]
