version: "3"
services:
  backend:
    image: ekkusi/arwi-backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION}
      JWT_ACCESS_TOKEN_SECRET_KEY: ${JWT_ACCESS_TOKEN_SECRET_KEY}
      JWT_REFRESH_TOKEN_SECRET_KEY: ${JWT_REFRESH_TOKEN_SECRET_KEY}
      MATOMO_BASE_URL: ${MATOMO_BASE_URL}
      MATOMO_SITE_ID: ${MATOMO_SITE_ID}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB_INDEX: 1
      MPASSID_CLIENT_SECRET: ${MPASSID_CLIENT_SECRET}
      MPASSID_CLIENT_ID: ${MPASSID_CLIENT_ID}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      APP_ENV: staging
    ports:
      - "4001:4000"
