version: "3"
services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: arwi
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - app-network
    restart: always

  mariadb:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: arwi-analytics
      MYSQL_USER: ${DB_USER}
    networks:
      - app-network

  matomo:
    image: matomo:fpm-alpine
    restart: always
    links:
      - mariadb
    volumes:
      - matomo:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: mariadb
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_USERNAME: ${DB_USER}
      MATOMO_DATABASE_PASSWORD: ${DB_PASSWORD}
      MATOMO_DATABASE_DBNAME: arwi-analytics
      PHP_MEMORY_LIMIT: 2048M
    ports:
      - 8080:80

  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   volumes:
  #     - matomo:/var/www/html:z,ro
  #     # see https://github.com/matomo-org/matomo-nginx
  #     - ./matomo-nginx.conf:/etc/nginx/conf.d/default.conf,ro
  #   ports:
  #     - 8080:80

  backend:
    image: ekkusi/arwi-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION}
      JWT_ACCESS_TOKEN_SECRET_KEY: ${JWT_ACCESS_TOKEN_SECRET_KEY}
      JWT_REFRESH_TOKEN_SECRET_KEY: ${JWT_REFRESH_TOKEN_SECRET_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - app-network

  web:
    image: ekkusi/arwi-web
    environment:
        NEXT_PUBLIC_GRIDLY_API_KEY: ${GRIDLY_API_KEY}
        NEXT_PUBLIC_GRIDLY_VIEW_ID: ${GRIDLY_API_KEY}
    ports:
      - "5000:3000"
    networks:
      - app-network
  
  
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
  pgadmin:
  mariadb:
  matomo:
