version: "3"
services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: arwi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: default@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped
  redis:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  pgadmin:
    driver: local
  redis_data:
    driver: local
