/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n  query Main_GetCurrentUser {\n    getCurrentUser {\n      email\n      languagePreference\n      consentsAnalytics\n      id\n      isMPassIDConnected\n    }\n  }\n": types.Main_GetCurrentUserDocument,
    "\n  query Main_GetAppMetadata {\n    getAppMetadata {\n      appVersion\n      minimumSupportedAppVersion\n      monthlyTokenUseLimit\n      feedbackGenerationTokenCost\n      textFixTokenCost\n    }\n  }\n": types.Main_GetAppMetadataDocument,
    "\n  mutation ClassParticipationEvaluationCard_FixTextGrammatics($studentId: ID!, $text: String!) {\n    fixTextGrammatics(studentId: $studentId, text: $text) {\n      result\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n": types.ClassParticipationEvaluationCard_FixTextGrammaticsDocument,
    "\n  fragment EvaluationsAccordion_Evaluation on ClassParticipationEvaluation {\n    id\n    notes\n    __typename\n    behaviourRating\n    skillsRating\n    collection {\n      date\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n    collection {\n      date\n    }\n    wasPresent\n    student {\n      name\n    }\n  }\n": types.EvaluationsAccordion_EvaluationFragmentDoc,
    "\n  mutation DefaultEvaluationCard_FixTextGrammatics($studentId: ID!, $text: String!) {\n    fixTextGrammatics(studentId: $studentId, text: $text) {\n      result\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n": types.DefaultEvaluationCard_FixTextGrammaticsDocument,
    "\n  fragment GroupListItem on Group {\n    id\n    name\n    archived\n    subject {\n      label {\n        fi\n      }\n      code\n    }\n    updatedAt\n  }\n": types.GroupListItemFragmentDoc,
    "\n  mutation GenerateFeedbacks_useGeneratedFeedbacks_Mutation($groupId: ID!) {\n    generateGroupFeedback(groupId: $groupId) {\n      feedbacks {\n        ...FeedbackCacheUpdate\n      }\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n": types.GenerateFeedbacks_UseGeneratedFeedbacks_MutationDocument,
    "\n  mutation MonthlyTokenUseWarning_SetTokenUseWarningSeen($warning: TokenUseWarning!) {\n    setTokenUseWarningSeen(warning: $warning)\n  }\n": types.MonthlyTokenUseWarning_SetTokenUseWarningSeenDocument,
    "\n  mutation MPassID_Login($code: String!) {\n    mPassIDLogin(code: $code) {\n      payload {\n        userData {\n          email\n          languagePreference\n          consentsAnalytics\n          id\n          isMPassIDConnected\n        }\n      }\n    }\n  }\n": types.MPassId_LoginDocument,
    "\n  query ArchivePage_GetCurrentUser {\n    getCurrentUser {\n      email\n      id\n      groups {\n        id\n        name\n        archived\n        updatedAt\n        subject {\n          label {\n            fi\n          }\n          code\n        }\n        currentModule {\n          id\n        }\n      }\n    }\n  }\n": types.ArchivePage_GetCurrentUserDocument,
    "\n  mutation CodeInput_VerifyPasswordResetCode($code: String!) {\n    verifyPasswordResetCode(code: $code)\n  }\n": types.CodeInput_VerifyPasswordResetCodeDocument,
    "\n  mutation ForgotPassword_RequestPasswordReset($email: String!) {\n    requestPasswordReset(email: $email)\n  }\n": types.ForgotPassword_RequestPasswordResetDocument,
    "\n  mutation LoginPage_Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      userData {\n        email\n        id\n        languagePreference\n        consentsAnalytics\n        isMPassIDConnected\n      }\n    }\n  }\n": types.LoginPage_LoginDocument,
    "\n  mutation RegisterPage_Register($input: CreateTeacherInput!) {\n    register(data: $input) {\n      userData {\n        email\n        id\n        languagePreference\n        consentsAnalytics\n        isMPassIDConnected\n      }\n    }\n  }\n": types.RegisterPage_RegisterDocument,
    "\n  mutation UpdatePasswordPage_UpdatePassword($code: String!, $newPassword: String!) {\n    updatePassword(recoveryCode: $code, newPassword: $newPassword)\n  }\n": types.UpdatePasswordPage_UpdatePasswordDocument,
    "\n  mutation AddNewStudent_CreateStudent($id: ID!, $input: CreateStudentInput!) {\n    createStudent(moduleId: $id, data: $input) {\n      id\n      group {\n        id\n        currentModule {\n          id\n          students {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.AddNewStudent_CreateStudentDocument,
    "\n  mutation ChangeArchiveStatus_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      id\n      archived\n    }\n  }\n": types.ChangeArchiveStatus_UpdateGroupDocument,
    "\n  query ChangeModule_GetGroup($id: ID!) {\n    getGroup(id: $id) {\n      id\n      subject {\n        code\n      }\n      currentModule {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n          label {\n            fi\n          }\n        }\n      }\n    }\n  }\n": types.ChangeModule_GetGroupDocument,
    "\n  mutation ChangeModule_ChangeModule($data: ChangeGroupModuleInput!, $groupId: ID!) {\n    changeGroupModule(data: $data, groupId: $groupId) {\n      id\n      currentModule {\n        id\n      }\n    }\n  }\n": types.ChangeModule_ChangeModuleDocument,
    "\n  mutation ChangeGroupName_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      id\n      name\n    }\n  }\n": types.ChangeGroupName_UpdateGroupDocument,
    "\n  mutation ChangeStudentName_UpdateStudent($id: ID!, $input: UpdateStudentInput!) {\n    updateStudent(studentId: $id, data: $input) {\n      id\n      name\n    }\n  }\n": types.ChangeStudentName_UpdateStudentDocument,
    "\n  mutation CollectionHeaderRightButton_DeleteCollection($id: ID!) {\n    deleteCollection(collectionId: $id) {\n      id\n      module {\n        id\n        evaluationCollections {\n          id\n        }\n        group {\n          id\n          currentModule {\n            id\n            collectionTypes {\n              id\n              defaultTypeCollection {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.CollectionHeaderRightButton_DeleteCollectionDocument,
    "\n  query MainPage_GetCurrentUser {\n    getCurrentUser {\n      email\n      id\n      groups {\n        id\n        name\n        archived\n        updatedAt\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n          }\n        }\n        subject {\n          label {\n            fi\n          }\n          code\n        }\n        currentModule {\n          id\n        }\n      }\n    }\n  }\n": types.MainPage_GetCurrentUserDocument,
    "\n  mutation StudentHeaderRightButton_DeleteStudent($id: ID!) {\n    deleteStudent(studentId: $id) {\n      id\n      group {\n        id\n        currentModule {\n          id\n          students {\n            id\n          }\n          evaluationCollections {\n            id\n            evaluations {\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n": types.StudentHeaderRightButton_DeleteStudentDocument,
    "\n  query ProfileView_GetCurrentUserUsageData {\n    getCurrentUserUsageData {\n      id\n      monthlyTokensUsed\n    }\n  }\n": types.ProfileView_GetCurrentUserUsageDataDocument,
    "\n  mutation ProfileView_Logout {\n    logout\n  }\n": types.ProfileView_LogoutDocument,
    "\n  mutation ProfileView_ConnectMPassID($code: String!) {\n    connectMPassID(code: $code) {\n      userData {\n        id\n        email\n        consentsAnalytics\n        languagePreference\n        isMPassIDConnected\n      }\n    }\n  }\n": types.ProfileView_ConnectMPassIdDocument,
    "\n  mutation ProfileView_ConnectLocalCredentials($email: String!, $password: String!) {\n    connectLocalCredentials(email: $email, password: $password) {\n      userData {\n        id\n        email\n        consentsAnalytics\n        languagePreference\n        isMPassIDConnected\n        groups {\n          id\n        }\n      }\n    }\n  }\n": types.ProfileView_ConnectLocalCredentialsDocument,
    "\n  fragment CollectionStatistics_EvaluationCollection on ClassParticipationCollection {\n    id\n    date\n    environment {\n      label {\n        fi\n      }\n      code\n    }\n    evaluations {\n      skillsRating\n      behaviourRating\n      wasPresent\n    }\n  }\n": types.CollectionStatistics_EvaluationCollectionFragmentDoc,
    "\n  fragment EvaluationsBarChart_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n": types.EvaluationsBarChart_EvaluationFragmentDoc,
    "\n  fragment EvaluationsHistogram_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n": types.EvaluationsHistogram_EvaluationFragmentDoc,
    "\n  fragment EvaluationStatistics_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      date\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n": types.EvaluationStatistics_EvaluationFragmentDoc,
    "\n  fragment ClassParticipationCollectionUpdate_GeneralInfoMinimal on ClassParticipationCollection {\n    id\n    date\n    description\n    environment {\n      label {\n        fi\n      }\n      code\n    }\n  }\n": types.ClassParticipationCollectionUpdate_GeneralInfoMinimalFragmentDoc,
    "\n  fragment ClassParticipationCollectionUpdate_GeneralInfoFull on ClassParticipationCollection {\n    ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n    learningObjectives {\n      code\n      label {\n        fi\n      }\n      description {\n        fi\n      }\n      type\n    }\n  }\n": types.ClassParticipationCollectionUpdate_GeneralInfoFullFragmentDoc,
    "\n  fragment DefaultCollectionUpdate_Info on DefaultCollection {\n    id\n    date\n    description\n  }\n": types.DefaultCollectionUpdate_InfoFragmentDoc,
    "\n  fragment ClassParticipationEvaluationUpdate_Info on ClassParticipationEvaluation {\n    id\n    wasPresent\n    skillsRating\n    behaviourRating\n    notes\n  }\n": types.ClassParticipationEvaluationUpdate_InfoFragmentDoc,
    "\n  fragment CollectionModuleCacheUpdate on Module {\n    id\n    evaluationCollections {\n      id\n    }\n    group {\n      id\n      updatedAt\n      teacher {\n        id\n        groups {\n          id\n          updatedAt\n        }\n      }\n    }\n  }\n": types.CollectionModuleCacheUpdateFragmentDoc,
    "\n  fragment DefaultEvaluationUpdate_Info on DefaultEvaluation {\n    id\n    wasPresent\n    rating\n    notes\n  }\n": types.DefaultEvaluationUpdate_InfoFragmentDoc,
    "\n  fragment GroupCollectionTypesUpdate_TypeInfo on CollectionType {\n    id\n    category\n    weight\n    name\n  }\n": types.GroupCollectionTypesUpdate_TypeInfoFragmentDoc,
    "\n  fragment GroupCollectionTypesUpdate on Group {\n    id\n    currentModule {\n      id\n      collectionTypes {\n        ...GroupCollectionTypesUpdate_TypeInfo\n      }\n    }\n  }\n": types.GroupCollectionTypesUpdateFragmentDoc,
    "\n  fragment FeedbackCacheUpdate on Feedback {\n    id\n    text\n    createdAt\n    student {\n      id\n      latestFeedback {\n        id\n      }\n      feedbacks {\n        id\n      }\n    }\n  }\n": types.FeedbackCacheUpdateFragmentDoc,
    "\n  query DefaultEvaluationCollection_GetCollectionType($typeId: ID!) {\n    getType(id: $typeId) {\n      id\n      category\n      name\n      weight\n      defaultTypeCollection {\n        id\n        date\n        evaluations {\n          id\n          student {\n            id\n            name\n          }\n          wasPresent\n          notes\n          rating\n        }\n      }\n      module {\n        id\n        group {\n          id\n        }\n      }\n    }\n  }\n": types.DefaultEvaluationCollection_GetCollectionTypeDocument,
    "\n  query DefaultCollectionEditAllEvaluationsView_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      evaluations {\n        id\n        wasPresent\n        __typename\n        ... on DefaultEvaluation {\n          rating\n        }\n        notes\n        student {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n    }\n  }\n": types.DefaultCollectionEditAllEvaluationsView_GetCollectionDocument,
    "\n  mutation DefaultCollectionEditAllEvaluationsView_UpdateCollection($updateCollectionInput: UpdateDefaultCollectionInput!, $collectionId: ID!) {\n    updateDefaultCollection(data: $updateCollectionInput, collectionId: $collectionId) {\n      id\n      evaluations {\n        ...DefaultEvaluationUpdate_Info\n      }\n    }\n  }\n": types.DefaultCollectionEditAllEvaluationsView_UpdateCollectionDocument,
    "\n  query CollectionEditAllEvaluationsView_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          code\n          label {\n            fi\n          }\n          color\n        }\n      }\n      evaluations {\n        id\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          skillsRating\n          behaviourRating\n        }\n        notes\n        student {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n    }\n  }\n": types.CollectionEditAllEvaluationsView_GetCollectionDocument,
    "\n  mutation CollectionEvaluationsView_UpdateCollection($updateCollectionInput: UpdateClassParticipationCollectionInput!, $collectionId: ID!) {\n    updateClassParticipationCollection(data: $updateCollectionInput, collectionId: $collectionId) {\n      id\n      evaluations {\n        ...ClassParticipationEvaluationUpdate_Info\n      }\n    }\n  }\n": types.CollectionEvaluationsView_UpdateCollectionDocument,
    "\n  query EditDefaultGeneralDetails_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      type {\n        id\n        name\n        category\n      }\n      module {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n        }\n        group {\n          id\n          subject {\n            code\n          }\n          currentModule {\n            collectionTypes {\n              id\n              name\n              category\n            }\n          }\n        }\n      }\n    }\n  }\n": types.EditDefaultGeneralDetails_GetCollectionDocument,
    "\n  mutation EditDefaultGeneralDetails_UpdateCollection($id: ID!, $input: UpdateDefaultCollectionInput!) {\n    updateDefaultCollection(collectionId: $id, data: $input) {\n      ...DefaultCollectionUpdate_Info\n    }\n  }\n": types.EditDefaultGeneralDetails_UpdateCollectionDocument,
    "\n  query EditGeneralDetails_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      type {\n        id\n        name\n        category\n      }\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          label {\n            fi\n          }\n          code\n          color\n        }\n        learningObjectives {\n          code\n          label {\n            fi\n          }\n          type\n        }\n      }\n      module {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n        }\n        group {\n          id\n          subject {\n            code\n          }\n          currentModule {\n            collectionTypes {\n              id\n              name\n              category\n            }\n          }\n        }\n      }\n    }\n  }\n": types.EditGeneralDetails_GetCollectionDocument,
    "\n  mutation EditGeneralDetails_UpdateCollection($id: ID!, $input: UpdateClassParticipationCollectionInput!) {\n    updateClassParticipationCollection(collectionId: $id, data: $input) {\n      ...ClassParticipationCollectionUpdate_GeneralInfoFull\n      evaluations {\n        id\n        collection {\n          ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n        }\n      }\n      module {\n        group {\n          id\n          currentModule {\n            id\n            evaluationCollections {\n              ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n            }\n          }\n        }\n      }\n    }\n  }\n": types.EditGeneralDetails_UpdateCollectionDocument,
    "\n  query CollectionPage_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          label {\n            fi\n          }\n          code\n          color\n        }\n        learningObjectives {\n          code\n          label {\n            fi\n          }\n        }\n      }\n      module {\n        group {\n          name\n          id\n        }\n      }\n      evaluations {\n        id\n        ...EvaluationsAccordion_Evaluation\n      }\n    }\n  }\n": types.CollectionPage_GetCollectionDocument,
    "\n  query DefaultEvaluationEditView_GetEvaluation($evaluationId: ID!) {\n    getEvaluation(id: $evaluationId) {\n      id\n      wasPresent\n      __typename\n      ... on DefaultEvaluation {\n        rating\n        collection {\n          id\n          date\n        }\n      }\n      notes\n      student {\n        id\n        name\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n    }\n  }\n": types.DefaultEvaluationEditView_GetEvaluationDocument,
    "\n  mutation DefaultEvaluationEditView_UpdateEvaluation($updateEvaluationInput: UpdateDefaultEvaluationInput!) {\n    updateDefaultEvaluation(input: $updateEvaluationInput) {\n      ...DefaultEvaluationUpdate_Info\n    }\n  }\n": types.DefaultEvaluationEditView_UpdateEvaluationDocument,
    "\n  query EvaluationEditView_GetEvaluation($evaluationId: ID!) {\n    getEvaluation(id: $evaluationId) {\n      id\n      wasPresent\n      __typename\n      ... on ClassParticipationEvaluation {\n        skillsRating\n        behaviourRating\n        collection {\n          id\n          date\n          environment {\n            code\n            label {\n              fi\n            }\n            color\n          }\n        }\n      }\n      notes\n      student {\n        id\n        name\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n    }\n  }\n": types.EvaluationEditView_GetEvaluationDocument,
    "\n  mutation EvaluationEditView_UpdateEvaluation($updateEvaluationInput: UpdateClassParticipationEvaluationInput!) {\n    updateClassParticipationEvaluation(input: $updateEvaluationInput) {\n      ...ClassParticipationEvaluationUpdate_Info\n      collection {\n        id\n        evaluations {\n          ...ClassParticipationEvaluationUpdate_Info\n        }\n      }\n    }\n  }\n": types.EvaluationEditView_UpdateEvaluationDocument,
    "\n  query FinalFeedback_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      name\n      archived\n      students {\n        id\n        latestFeedback {\n          id\n        }\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n      currentModule {\n        id\n        evaluationCollections {\n          id\n          type {\n            id\n            category\n          }\n        }\n        collectionTypes {\n          id\n          category\n          name\n          weight\n          defaultTypeCollection {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.FinalFeedback_GetGroupDocument,
    "\n  query FinalFeedbackItem_GetStudent($studentId: ID!) {\n    getStudent(id: $studentId) {\n      id\n      name\n      latestFeedback {\n        id\n        text\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              code\n              label {\n                fi\n              }\n            }\n          }\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n": types.FinalFeedbackItem_GetStudentDocument,
    "\n  query GroupOverviewPage_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      name\n      archived\n      subject {\n        label {\n          fi\n        }\n        code\n      }\n      currentModule {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n          label {\n            fi\n          }\n        }\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            wasPresent\n          }\n        }\n        evaluationCollections {\n          id\n          date\n          type {\n            id\n            category\n          }\n          __typename\n          ... on ClassParticipationCollection {\n            environment {\n              label {\n                fi\n              }\n              code\n              color\n            }\n            learningObjectives {\n              code\n              label {\n                fi\n              }\n              description {\n                fi\n              }\n              type\n            }\n            ...CollectionStatistics_EvaluationCollection\n          }\n        }\n      }\n      currentModule {\n        id\n        collectionTypes {\n          id\n          category\n          name\n          weight\n          defaultTypeCollection {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GroupOverviewPage_GetGroupDocument,
    "\n  query StudentFeedbackView_GetStudent($id: ID!) {\n    getStudent(id: $id) {\n      id\n      group {\n        id\n        archived\n        currentModule {\n          id\n        }\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n          }\n        }\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              label {\n                fi\n              }\n              code\n              color\n            }\n          }\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n": types.StudentFeedbackView_GetStudentDocument,
    "\n  mutation StudentFeedbackView_GenerateFeedback($studentId: ID!, $moduleId: ID!) {\n    generateStudentFeedback(studentId: $studentId, moduleId: $moduleId) {\n      feedback {\n        text\n        ...FeedbackCacheUpdate\n      }\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n": types.StudentFeedbackView_GenerateFeedbackDocument,
    "\n  query StudentPage_GetStudent($studentId: ID!) {\n    getStudent(id: $studentId) {\n      id\n      name\n      group {\n        id\n        name\n        subject {\n          code\n          label {\n            fi\n          }\n        }\n        currentModule {\n          id\n          info {\n            educationLevel\n            learningObjectiveGroupKey\n            label {\n              fi\n            }\n          }\n        }\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n            defaultTypeCollection {\n              id\n            }\n          }\n        }\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              code\n              label {\n                fi\n              }\n            }\n          }\n          ...EvaluationStatistics_Evaluation\n          ...EvaluationsBarChart_Evaluation\n          ...EvaluationsHistogram_Evaluation\n          ...EvaluationsAccordion_Evaluation\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n": types.StudentPage_GetStudentDocument,
    "\n  query CollectionCreationProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        id\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n      currentModule {\n        collectionTypes {\n          id\n          name\n          category\n        }\n      }\n      ...CollectionGeneralInfoView_Group\n    }\n  }\n": types.CollectionCreationProvider_GetGroupDocument,
    "\n  mutation CollectionEvaluationsView_CreateCollection($createCollectionInput: CreateClassParticipationCollectionInput!, $moduleId: ID!) {\n    createClassParticipationCollection(data: $createCollectionInput, moduleId: $moduleId) {\n      ...ClassParticipationCollectionUpdate_GeneralInfoFull\n      evaluations {\n        ...ClassParticipationEvaluationUpdate_Info\n        student {\n          id\n          currentModuleEvaluations {\n            id\n          }\n        }\n      }\n      module {\n        ...CollectionModuleCacheUpdate\n      }\n    }\n  }\n": types.CollectionEvaluationsView_CreateCollectionDocument,
    "\n  fragment CollectionGeneralInfoView_Group on Group {\n    subject {\n      code\n    }\n    currentModule {\n      id\n      info {\n        educationLevel\n        learningObjectiveGroupKey\n      }\n    }\n  }\n": types.CollectionGeneralInfoView_GroupFragmentDoc,
    "\n  fragment CollectionParticipationsView_Group on Group {\n    students {\n      id\n      name\n    }\n  }\n": types.CollectionParticipationsView_GroupFragmentDoc,
    "\n  mutation CreateGroupPage_CreateGroup($input: CreateGroupInput!) {\n    createGroup(data: $input) {\n      id\n    }\n  }\n": types.CreateGroupPage_CreateGroupDocument,
    "\n  mutation EditTypeWeightsView_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      ...GroupCollectionTypesUpdate\n    }\n  }\n": types.EditTypeWeightsView_UpdateGroupDocument,
    "\n  query UpdateTypesProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        collectionTypes {\n          id\n          category\n          name\n          weight\n        }\n      }\n    }\n  }\n": types.UpdateTypesProvider_GetGroupDocument,
    "\n  query DefaultCollectionCreationProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        id\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n      currentModule {\n        collectionTypes {\n          id\n          name\n          category\n        }\n      }\n      ...CollectionGeneralInfoView_Group\n    }\n  }\n": types.DefaultCollectionCreationProvider_GetGroupDocument,
    "\n  mutation DefaultCollectionEvaluationsView_CreateCollection($createCollectionInput: CreateDefaultCollectionInput!, $moduleId: ID!) {\n    createDefaultCollection(data: $createCollectionInput, moduleId: $moduleId) {\n      ...DefaultCollectionUpdate_Info\n      evaluations {\n        ...DefaultEvaluationUpdate_Info\n        student {\n          id\n          currentModuleEvaluations {\n            id\n          }\n        }\n      }\n      module {\n        ...CollectionModuleCacheUpdate\n      }\n    }\n  }\n": types.DefaultCollectionEvaluationsView_CreateCollectionDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Main_GetCurrentUser {\n    getCurrentUser {\n      email\n      languagePreference\n      consentsAnalytics\n      id\n      isMPassIDConnected\n    }\n  }\n"): (typeof documents)["\n  query Main_GetCurrentUser {\n    getCurrentUser {\n      email\n      languagePreference\n      consentsAnalytics\n      id\n      isMPassIDConnected\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Main_GetAppMetadata {\n    getAppMetadata {\n      appVersion\n      minimumSupportedAppVersion\n      monthlyTokenUseLimit\n      feedbackGenerationTokenCost\n      textFixTokenCost\n    }\n  }\n"): (typeof documents)["\n  query Main_GetAppMetadata {\n    getAppMetadata {\n      appVersion\n      minimumSupportedAppVersion\n      monthlyTokenUseLimit\n      feedbackGenerationTokenCost\n      textFixTokenCost\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ClassParticipationEvaluationCard_FixTextGrammatics($studentId: ID!, $text: String!) {\n    fixTextGrammatics(studentId: $studentId, text: $text) {\n      result\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ClassParticipationEvaluationCard_FixTextGrammatics($studentId: ID!, $text: String!) {\n    fixTextGrammatics(studentId: $studentId, text: $text) {\n      result\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment EvaluationsAccordion_Evaluation on ClassParticipationEvaluation {\n    id\n    notes\n    __typename\n    behaviourRating\n    skillsRating\n    collection {\n      date\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n    collection {\n      date\n    }\n    wasPresent\n    student {\n      name\n    }\n  }\n"): (typeof documents)["\n  fragment EvaluationsAccordion_Evaluation on ClassParticipationEvaluation {\n    id\n    notes\n    __typename\n    behaviourRating\n    skillsRating\n    collection {\n      date\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n    collection {\n      date\n    }\n    wasPresent\n    student {\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DefaultEvaluationCard_FixTextGrammatics($studentId: ID!, $text: String!) {\n    fixTextGrammatics(studentId: $studentId, text: $text) {\n      result\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DefaultEvaluationCard_FixTextGrammatics($studentId: ID!, $text: String!) {\n    fixTextGrammatics(studentId: $studentId, text: $text) {\n      result\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment GroupListItem on Group {\n    id\n    name\n    archived\n    subject {\n      label {\n        fi\n      }\n      code\n    }\n    updatedAt\n  }\n"): (typeof documents)["\n  fragment GroupListItem on Group {\n    id\n    name\n    archived\n    subject {\n      label {\n        fi\n      }\n      code\n    }\n    updatedAt\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation GenerateFeedbacks_useGeneratedFeedbacks_Mutation($groupId: ID!) {\n    generateGroupFeedback(groupId: $groupId) {\n      feedbacks {\n        ...FeedbackCacheUpdate\n      }\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation GenerateFeedbacks_useGeneratedFeedbacks_Mutation($groupId: ID!) {\n    generateGroupFeedback(groupId: $groupId) {\n      feedbacks {\n        ...FeedbackCacheUpdate\n      }\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MonthlyTokenUseWarning_SetTokenUseWarningSeen($warning: TokenUseWarning!) {\n    setTokenUseWarningSeen(warning: $warning)\n  }\n"): (typeof documents)["\n  mutation MonthlyTokenUseWarning_SetTokenUseWarningSeen($warning: TokenUseWarning!) {\n    setTokenUseWarningSeen(warning: $warning)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MPassID_Login($code: String!) {\n    mPassIDLogin(code: $code) {\n      payload {\n        userData {\n          email\n          languagePreference\n          consentsAnalytics\n          id\n          isMPassIDConnected\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation MPassID_Login($code: String!) {\n    mPassIDLogin(code: $code) {\n      payload {\n        userData {\n          email\n          languagePreference\n          consentsAnalytics\n          id\n          isMPassIDConnected\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ArchivePage_GetCurrentUser {\n    getCurrentUser {\n      email\n      id\n      groups {\n        id\n        name\n        archived\n        updatedAt\n        subject {\n          label {\n            fi\n          }\n          code\n        }\n        currentModule {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ArchivePage_GetCurrentUser {\n    getCurrentUser {\n      email\n      id\n      groups {\n        id\n        name\n        archived\n        updatedAt\n        subject {\n          label {\n            fi\n          }\n          code\n        }\n        currentModule {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CodeInput_VerifyPasswordResetCode($code: String!) {\n    verifyPasswordResetCode(code: $code)\n  }\n"): (typeof documents)["\n  mutation CodeInput_VerifyPasswordResetCode($code: String!) {\n    verifyPasswordResetCode(code: $code)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ForgotPassword_RequestPasswordReset($email: String!) {\n    requestPasswordReset(email: $email)\n  }\n"): (typeof documents)["\n  mutation ForgotPassword_RequestPasswordReset($email: String!) {\n    requestPasswordReset(email: $email)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation LoginPage_Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      userData {\n        email\n        id\n        languagePreference\n        consentsAnalytics\n        isMPassIDConnected\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation LoginPage_Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      userData {\n        email\n        id\n        languagePreference\n        consentsAnalytics\n        isMPassIDConnected\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RegisterPage_Register($input: CreateTeacherInput!) {\n    register(data: $input) {\n      userData {\n        email\n        id\n        languagePreference\n        consentsAnalytics\n        isMPassIDConnected\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation RegisterPage_Register($input: CreateTeacherInput!) {\n    register(data: $input) {\n      userData {\n        email\n        id\n        languagePreference\n        consentsAnalytics\n        isMPassIDConnected\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdatePasswordPage_UpdatePassword($code: String!, $newPassword: String!) {\n    updatePassword(recoveryCode: $code, newPassword: $newPassword)\n  }\n"): (typeof documents)["\n  mutation UpdatePasswordPage_UpdatePassword($code: String!, $newPassword: String!) {\n    updatePassword(recoveryCode: $code, newPassword: $newPassword)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddNewStudent_CreateStudent($id: ID!, $input: CreateStudentInput!) {\n    createStudent(moduleId: $id, data: $input) {\n      id\n      group {\n        id\n        currentModule {\n          id\n          students {\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AddNewStudent_CreateStudent($id: ID!, $input: CreateStudentInput!) {\n    createStudent(moduleId: $id, data: $input) {\n      id\n      group {\n        id\n        currentModule {\n          id\n          students {\n            id\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ChangeArchiveStatus_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      id\n      archived\n    }\n  }\n"): (typeof documents)["\n  mutation ChangeArchiveStatus_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      id\n      archived\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ChangeModule_GetGroup($id: ID!) {\n    getGroup(id: $id) {\n      id\n      subject {\n        code\n      }\n      currentModule {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n          label {\n            fi\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ChangeModule_GetGroup($id: ID!) {\n    getGroup(id: $id) {\n      id\n      subject {\n        code\n      }\n      currentModule {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n          label {\n            fi\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ChangeModule_ChangeModule($data: ChangeGroupModuleInput!, $groupId: ID!) {\n    changeGroupModule(data: $data, groupId: $groupId) {\n      id\n      currentModule {\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ChangeModule_ChangeModule($data: ChangeGroupModuleInput!, $groupId: ID!) {\n    changeGroupModule(data: $data, groupId: $groupId) {\n      id\n      currentModule {\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ChangeGroupName_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation ChangeGroupName_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ChangeStudentName_UpdateStudent($id: ID!, $input: UpdateStudentInput!) {\n    updateStudent(studentId: $id, data: $input) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation ChangeStudentName_UpdateStudent($id: ID!, $input: UpdateStudentInput!) {\n    updateStudent(studentId: $id, data: $input) {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CollectionHeaderRightButton_DeleteCollection($id: ID!) {\n    deleteCollection(collectionId: $id) {\n      id\n      module {\n        id\n        evaluationCollections {\n          id\n        }\n        group {\n          id\n          currentModule {\n            id\n            collectionTypes {\n              id\n              defaultTypeCollection {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CollectionHeaderRightButton_DeleteCollection($id: ID!) {\n    deleteCollection(collectionId: $id) {\n      id\n      module {\n        id\n        evaluationCollections {\n          id\n        }\n        group {\n          id\n          currentModule {\n            id\n            collectionTypes {\n              id\n              defaultTypeCollection {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MainPage_GetCurrentUser {\n    getCurrentUser {\n      email\n      id\n      groups {\n        id\n        name\n        archived\n        updatedAt\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n          }\n        }\n        subject {\n          label {\n            fi\n          }\n          code\n        }\n        currentModule {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query MainPage_GetCurrentUser {\n    getCurrentUser {\n      email\n      id\n      groups {\n        id\n        name\n        archived\n        updatedAt\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n          }\n        }\n        subject {\n          label {\n            fi\n          }\n          code\n        }\n        currentModule {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation StudentHeaderRightButton_DeleteStudent($id: ID!) {\n    deleteStudent(studentId: $id) {\n      id\n      group {\n        id\n        currentModule {\n          id\n          students {\n            id\n          }\n          evaluationCollections {\n            id\n            evaluations {\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation StudentHeaderRightButton_DeleteStudent($id: ID!) {\n    deleteStudent(studentId: $id) {\n      id\n      group {\n        id\n        currentModule {\n          id\n          students {\n            id\n          }\n          evaluationCollections {\n            id\n            evaluations {\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProfileView_GetCurrentUserUsageData {\n    getCurrentUserUsageData {\n      id\n      monthlyTokensUsed\n    }\n  }\n"): (typeof documents)["\n  query ProfileView_GetCurrentUserUsageData {\n    getCurrentUserUsageData {\n      id\n      monthlyTokensUsed\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ProfileView_Logout {\n    logout\n  }\n"): (typeof documents)["\n  mutation ProfileView_Logout {\n    logout\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ProfileView_ConnectMPassID($code: String!) {\n    connectMPassID(code: $code) {\n      userData {\n        id\n        email\n        consentsAnalytics\n        languagePreference\n        isMPassIDConnected\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ProfileView_ConnectMPassID($code: String!) {\n    connectMPassID(code: $code) {\n      userData {\n        id\n        email\n        consentsAnalytics\n        languagePreference\n        isMPassIDConnected\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ProfileView_ConnectLocalCredentials($email: String!, $password: String!) {\n    connectLocalCredentials(email: $email, password: $password) {\n      userData {\n        id\n        email\n        consentsAnalytics\n        languagePreference\n        isMPassIDConnected\n        groups {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ProfileView_ConnectLocalCredentials($email: String!, $password: String!) {\n    connectLocalCredentials(email: $email, password: $password) {\n      userData {\n        id\n        email\n        consentsAnalytics\n        languagePreference\n        isMPassIDConnected\n        groups {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment CollectionStatistics_EvaluationCollection on ClassParticipationCollection {\n    id\n    date\n    environment {\n      label {\n        fi\n      }\n      code\n    }\n    evaluations {\n      skillsRating\n      behaviourRating\n      wasPresent\n    }\n  }\n"): (typeof documents)["\n  fragment CollectionStatistics_EvaluationCollection on ClassParticipationCollection {\n    id\n    date\n    environment {\n      label {\n        fi\n      }\n      code\n    }\n    evaluations {\n      skillsRating\n      behaviourRating\n      wasPresent\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment EvaluationsBarChart_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment EvaluationsBarChart_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment EvaluationsHistogram_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment EvaluationsHistogram_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment EvaluationStatistics_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      date\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment EvaluationStatistics_Evaluation on ClassParticipationEvaluation {\n    id\n    skillsRating\n    behaviourRating\n    wasPresent\n    collection {\n      date\n      environment {\n        label {\n          fi\n        }\n        code\n        color\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment ClassParticipationCollectionUpdate_GeneralInfoMinimal on ClassParticipationCollection {\n    id\n    date\n    description\n    environment {\n      label {\n        fi\n      }\n      code\n    }\n  }\n"): (typeof documents)["\n  fragment ClassParticipationCollectionUpdate_GeneralInfoMinimal on ClassParticipationCollection {\n    id\n    date\n    description\n    environment {\n      label {\n        fi\n      }\n      code\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment ClassParticipationCollectionUpdate_GeneralInfoFull on ClassParticipationCollection {\n    ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n    learningObjectives {\n      code\n      label {\n        fi\n      }\n      description {\n        fi\n      }\n      type\n    }\n  }\n"): (typeof documents)["\n  fragment ClassParticipationCollectionUpdate_GeneralInfoFull on ClassParticipationCollection {\n    ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n    learningObjectives {\n      code\n      label {\n        fi\n      }\n      description {\n        fi\n      }\n      type\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DefaultCollectionUpdate_Info on DefaultCollection {\n    id\n    date\n    description\n  }\n"): (typeof documents)["\n  fragment DefaultCollectionUpdate_Info on DefaultCollection {\n    id\n    date\n    description\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment ClassParticipationEvaluationUpdate_Info on ClassParticipationEvaluation {\n    id\n    wasPresent\n    skillsRating\n    behaviourRating\n    notes\n  }\n"): (typeof documents)["\n  fragment ClassParticipationEvaluationUpdate_Info on ClassParticipationEvaluation {\n    id\n    wasPresent\n    skillsRating\n    behaviourRating\n    notes\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment CollectionModuleCacheUpdate on Module {\n    id\n    evaluationCollections {\n      id\n    }\n    group {\n      id\n      updatedAt\n      teacher {\n        id\n        groups {\n          id\n          updatedAt\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment CollectionModuleCacheUpdate on Module {\n    id\n    evaluationCollections {\n      id\n    }\n    group {\n      id\n      updatedAt\n      teacher {\n        id\n        groups {\n          id\n          updatedAt\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DefaultEvaluationUpdate_Info on DefaultEvaluation {\n    id\n    wasPresent\n    rating\n    notes\n  }\n"): (typeof documents)["\n  fragment DefaultEvaluationUpdate_Info on DefaultEvaluation {\n    id\n    wasPresent\n    rating\n    notes\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment GroupCollectionTypesUpdate_TypeInfo on CollectionType {\n    id\n    category\n    weight\n    name\n  }\n"): (typeof documents)["\n  fragment GroupCollectionTypesUpdate_TypeInfo on CollectionType {\n    id\n    category\n    weight\n    name\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment GroupCollectionTypesUpdate on Group {\n    id\n    currentModule {\n      id\n      collectionTypes {\n        ...GroupCollectionTypesUpdate_TypeInfo\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment GroupCollectionTypesUpdate on Group {\n    id\n    currentModule {\n      id\n      collectionTypes {\n        ...GroupCollectionTypesUpdate_TypeInfo\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment FeedbackCacheUpdate on Feedback {\n    id\n    text\n    createdAt\n    student {\n      id\n      latestFeedback {\n        id\n      }\n      feedbacks {\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment FeedbackCacheUpdate on Feedback {\n    id\n    text\n    createdAt\n    student {\n      id\n      latestFeedback {\n        id\n      }\n      feedbacks {\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DefaultEvaluationCollection_GetCollectionType($typeId: ID!) {\n    getType(id: $typeId) {\n      id\n      category\n      name\n      weight\n      defaultTypeCollection {\n        id\n        date\n        evaluations {\n          id\n          student {\n            id\n            name\n          }\n          wasPresent\n          notes\n          rating\n        }\n      }\n      module {\n        id\n        group {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query DefaultEvaluationCollection_GetCollectionType($typeId: ID!) {\n    getType(id: $typeId) {\n      id\n      category\n      name\n      weight\n      defaultTypeCollection {\n        id\n        date\n        evaluations {\n          id\n          student {\n            id\n            name\n          }\n          wasPresent\n          notes\n          rating\n        }\n      }\n      module {\n        id\n        group {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DefaultCollectionEditAllEvaluationsView_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      evaluations {\n        id\n        wasPresent\n        __typename\n        ... on DefaultEvaluation {\n          rating\n        }\n        notes\n        student {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query DefaultCollectionEditAllEvaluationsView_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      evaluations {\n        id\n        wasPresent\n        __typename\n        ... on DefaultEvaluation {\n          rating\n        }\n        notes\n        student {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DefaultCollectionEditAllEvaluationsView_UpdateCollection($updateCollectionInput: UpdateDefaultCollectionInput!, $collectionId: ID!) {\n    updateDefaultCollection(data: $updateCollectionInput, collectionId: $collectionId) {\n      id\n      evaluations {\n        ...DefaultEvaluationUpdate_Info\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DefaultCollectionEditAllEvaluationsView_UpdateCollection($updateCollectionInput: UpdateDefaultCollectionInput!, $collectionId: ID!) {\n    updateDefaultCollection(data: $updateCollectionInput, collectionId: $collectionId) {\n      id\n      evaluations {\n        ...DefaultEvaluationUpdate_Info\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CollectionEditAllEvaluationsView_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          code\n          label {\n            fi\n          }\n          color\n        }\n      }\n      evaluations {\n        id\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          skillsRating\n          behaviourRating\n        }\n        notes\n        student {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query CollectionEditAllEvaluationsView_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          code\n          label {\n            fi\n          }\n          color\n        }\n      }\n      evaluations {\n        id\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          skillsRating\n          behaviourRating\n        }\n        notes\n        student {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CollectionEvaluationsView_UpdateCollection($updateCollectionInput: UpdateClassParticipationCollectionInput!, $collectionId: ID!) {\n    updateClassParticipationCollection(data: $updateCollectionInput, collectionId: $collectionId) {\n      id\n      evaluations {\n        ...ClassParticipationEvaluationUpdate_Info\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CollectionEvaluationsView_UpdateCollection($updateCollectionInput: UpdateClassParticipationCollectionInput!, $collectionId: ID!) {\n    updateClassParticipationCollection(data: $updateCollectionInput, collectionId: $collectionId) {\n      id\n      evaluations {\n        ...ClassParticipationEvaluationUpdate_Info\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EditDefaultGeneralDetails_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      type {\n        id\n        name\n        category\n      }\n      module {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n        }\n        group {\n          id\n          subject {\n            code\n          }\n          currentModule {\n            collectionTypes {\n              id\n              name\n              category\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query EditDefaultGeneralDetails_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      type {\n        id\n        name\n        category\n      }\n      module {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n        }\n        group {\n          id\n          subject {\n            code\n          }\n          currentModule {\n            collectionTypes {\n              id\n              name\n              category\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation EditDefaultGeneralDetails_UpdateCollection($id: ID!, $input: UpdateDefaultCollectionInput!) {\n    updateDefaultCollection(collectionId: $id, data: $input) {\n      ...DefaultCollectionUpdate_Info\n    }\n  }\n"): (typeof documents)["\n  mutation EditDefaultGeneralDetails_UpdateCollection($id: ID!, $input: UpdateDefaultCollectionInput!) {\n    updateDefaultCollection(collectionId: $id, data: $input) {\n      ...DefaultCollectionUpdate_Info\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EditGeneralDetails_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      type {\n        id\n        name\n        category\n      }\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          label {\n            fi\n          }\n          code\n          color\n        }\n        learningObjectives {\n          code\n          label {\n            fi\n          }\n          type\n        }\n      }\n      module {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n        }\n        group {\n          id\n          subject {\n            code\n          }\n          currentModule {\n            collectionTypes {\n              id\n              name\n              category\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query EditGeneralDetails_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      type {\n        id\n        name\n        category\n      }\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          label {\n            fi\n          }\n          code\n          color\n        }\n        learningObjectives {\n          code\n          label {\n            fi\n          }\n          type\n        }\n      }\n      module {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n        }\n        group {\n          id\n          subject {\n            code\n          }\n          currentModule {\n            collectionTypes {\n              id\n              name\n              category\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation EditGeneralDetails_UpdateCollection($id: ID!, $input: UpdateClassParticipationCollectionInput!) {\n    updateClassParticipationCollection(collectionId: $id, data: $input) {\n      ...ClassParticipationCollectionUpdate_GeneralInfoFull\n      evaluations {\n        id\n        collection {\n          ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n        }\n      }\n      module {\n        group {\n          id\n          currentModule {\n            id\n            evaluationCollections {\n              ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation EditGeneralDetails_UpdateCollection($id: ID!, $input: UpdateClassParticipationCollectionInput!) {\n    updateClassParticipationCollection(collectionId: $id, data: $input) {\n      ...ClassParticipationCollectionUpdate_GeneralInfoFull\n      evaluations {\n        id\n        collection {\n          ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n        }\n      }\n      module {\n        group {\n          id\n          currentModule {\n            id\n            evaluationCollections {\n              ...ClassParticipationCollectionUpdate_GeneralInfoMinimal\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CollectionPage_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          label {\n            fi\n          }\n          code\n          color\n        }\n        learningObjectives {\n          code\n          label {\n            fi\n          }\n        }\n      }\n      module {\n        group {\n          name\n          id\n        }\n      }\n      evaluations {\n        id\n        ...EvaluationsAccordion_Evaluation\n      }\n    }\n  }\n"): (typeof documents)["\n  query CollectionPage_GetCollection($collectionId: ID!) {\n    getCollection(id: $collectionId) {\n      id\n      date\n      description\n      __typename\n      ... on ClassParticipationCollection {\n        environment {\n          label {\n            fi\n          }\n          code\n          color\n        }\n        learningObjectives {\n          code\n          label {\n            fi\n          }\n        }\n      }\n      module {\n        group {\n          name\n          id\n        }\n      }\n      evaluations {\n        id\n        ...EvaluationsAccordion_Evaluation\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DefaultEvaluationEditView_GetEvaluation($evaluationId: ID!) {\n    getEvaluation(id: $evaluationId) {\n      id\n      wasPresent\n      __typename\n      ... on DefaultEvaluation {\n        rating\n        collection {\n          id\n          date\n        }\n      }\n      notes\n      student {\n        id\n        name\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query DefaultEvaluationEditView_GetEvaluation($evaluationId: ID!) {\n    getEvaluation(id: $evaluationId) {\n      id\n      wasPresent\n      __typename\n      ... on DefaultEvaluation {\n        rating\n        collection {\n          id\n          date\n        }\n      }\n      notes\n      student {\n        id\n        name\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DefaultEvaluationEditView_UpdateEvaluation($updateEvaluationInput: UpdateDefaultEvaluationInput!) {\n    updateDefaultEvaluation(input: $updateEvaluationInput) {\n      ...DefaultEvaluationUpdate_Info\n    }\n  }\n"): (typeof documents)["\n  mutation DefaultEvaluationEditView_UpdateEvaluation($updateEvaluationInput: UpdateDefaultEvaluationInput!) {\n    updateDefaultEvaluation(input: $updateEvaluationInput) {\n      ...DefaultEvaluationUpdate_Info\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EvaluationEditView_GetEvaluation($evaluationId: ID!) {\n    getEvaluation(id: $evaluationId) {\n      id\n      wasPresent\n      __typename\n      ... on ClassParticipationEvaluation {\n        skillsRating\n        behaviourRating\n        collection {\n          id\n          date\n          environment {\n            code\n            label {\n              fi\n            }\n            color\n          }\n        }\n      }\n      notes\n      student {\n        id\n        name\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query EvaluationEditView_GetEvaluation($evaluationId: ID!) {\n    getEvaluation(id: $evaluationId) {\n      id\n      wasPresent\n      __typename\n      ... on ClassParticipationEvaluation {\n        skillsRating\n        behaviourRating\n        collection {\n          id\n          date\n          environment {\n            code\n            label {\n              fi\n            }\n            color\n          }\n        }\n      }\n      notes\n      student {\n        id\n        name\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation EvaluationEditView_UpdateEvaluation($updateEvaluationInput: UpdateClassParticipationEvaluationInput!) {\n    updateClassParticipationEvaluation(input: $updateEvaluationInput) {\n      ...ClassParticipationEvaluationUpdate_Info\n      collection {\n        id\n        evaluations {\n          ...ClassParticipationEvaluationUpdate_Info\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation EvaluationEditView_UpdateEvaluation($updateEvaluationInput: UpdateClassParticipationEvaluationInput!) {\n    updateClassParticipationEvaluation(input: $updateEvaluationInput) {\n      ...ClassParticipationEvaluationUpdate_Info\n      collection {\n        id\n        evaluations {\n          ...ClassParticipationEvaluationUpdate_Info\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FinalFeedback_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      name\n      archived\n      students {\n        id\n        latestFeedback {\n          id\n        }\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n      currentModule {\n        id\n        evaluationCollections {\n          id\n          type {\n            id\n            category\n          }\n        }\n        collectionTypes {\n          id\n          category\n          name\n          weight\n          defaultTypeCollection {\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FinalFeedback_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      name\n      archived\n      students {\n        id\n        latestFeedback {\n          id\n        }\n        currentModuleEvaluations {\n          id\n          notes\n        }\n      }\n      currentModule {\n        id\n        evaluationCollections {\n          id\n          type {\n            id\n            category\n          }\n        }\n        collectionTypes {\n          id\n          category\n          name\n          weight\n          defaultTypeCollection {\n            id\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FinalFeedbackItem_GetStudent($studentId: ID!) {\n    getStudent(id: $studentId) {\n      id\n      name\n      latestFeedback {\n        id\n        text\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              code\n              label {\n                fi\n              }\n            }\n          }\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FinalFeedbackItem_GetStudent($studentId: ID!) {\n    getStudent(id: $studentId) {\n      id\n      name\n      latestFeedback {\n        id\n        text\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              code\n              label {\n                fi\n              }\n            }\n          }\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GroupOverviewPage_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      name\n      archived\n      subject {\n        label {\n          fi\n        }\n        code\n      }\n      currentModule {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n          label {\n            fi\n          }\n        }\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            wasPresent\n          }\n        }\n        evaluationCollections {\n          id\n          date\n          type {\n            id\n            category\n          }\n          __typename\n          ... on ClassParticipationCollection {\n            environment {\n              label {\n                fi\n              }\n              code\n              color\n            }\n            learningObjectives {\n              code\n              label {\n                fi\n              }\n              description {\n                fi\n              }\n              type\n            }\n            ...CollectionStatistics_EvaluationCollection\n          }\n        }\n      }\n      currentModule {\n        id\n        collectionTypes {\n          id\n          category\n          name\n          weight\n          defaultTypeCollection {\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GroupOverviewPage_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      name\n      archived\n      subject {\n        label {\n          fi\n        }\n        code\n      }\n      currentModule {\n        id\n        info {\n          educationLevel\n          learningObjectiveGroupKey\n          label {\n            fi\n          }\n        }\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            wasPresent\n          }\n        }\n        evaluationCollections {\n          id\n          date\n          type {\n            id\n            category\n          }\n          __typename\n          ... on ClassParticipationCollection {\n            environment {\n              label {\n                fi\n              }\n              code\n              color\n            }\n            learningObjectives {\n              code\n              label {\n                fi\n              }\n              description {\n                fi\n              }\n              type\n            }\n            ...CollectionStatistics_EvaluationCollection\n          }\n        }\n      }\n      currentModule {\n        id\n        collectionTypes {\n          id\n          category\n          name\n          weight\n          defaultTypeCollection {\n            id\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query StudentFeedbackView_GetStudent($id: ID!) {\n    getStudent(id: $id) {\n      id\n      group {\n        id\n        archived\n        currentModule {\n          id\n        }\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n          }\n        }\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              label {\n                fi\n              }\n              code\n              color\n            }\n          }\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query StudentFeedbackView_GetStudent($id: ID!) {\n    getStudent(id: $id) {\n      id\n      group {\n        id\n        archived\n        currentModule {\n          id\n        }\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n          }\n        }\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              label {\n                fi\n              }\n              code\n              color\n            }\n          }\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation StudentFeedbackView_GenerateFeedback($studentId: ID!, $moduleId: ID!) {\n    generateStudentFeedback(studentId: $studentId, moduleId: $moduleId) {\n      feedback {\n        text\n        ...FeedbackCacheUpdate\n      }\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation StudentFeedbackView_GenerateFeedback($studentId: ID!, $moduleId: ID!) {\n    generateStudentFeedback(studentId: $studentId, moduleId: $moduleId) {\n      feedback {\n        text\n        ...FeedbackCacheUpdate\n      }\n      usageData {\n        id\n        monthlyTokensUsed\n        warning {\n          warning\n          threshhold\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query StudentPage_GetStudent($studentId: ID!) {\n    getStudent(id: $studentId) {\n      id\n      name\n      group {\n        id\n        name\n        subject {\n          code\n          label {\n            fi\n          }\n        }\n        currentModule {\n          id\n          info {\n            educationLevel\n            learningObjectiveGroupKey\n            label {\n              fi\n            }\n          }\n        }\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n            defaultTypeCollection {\n              id\n            }\n          }\n        }\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              code\n              label {\n                fi\n              }\n            }\n          }\n          ...EvaluationStatistics_Evaluation\n          ...EvaluationsBarChart_Evaluation\n          ...EvaluationsHistogram_Evaluation\n          ...EvaluationsAccordion_Evaluation\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query StudentPage_GetStudent($studentId: ID!) {\n    getStudent(id: $studentId) {\n      id\n      name\n      group {\n        id\n        name\n        subject {\n          code\n          label {\n            fi\n          }\n        }\n        currentModule {\n          id\n          info {\n            educationLevel\n            learningObjectiveGroupKey\n            label {\n              fi\n            }\n          }\n        }\n        currentModule {\n          collectionTypes {\n            id\n            category\n            name\n            weight\n            defaultTypeCollection {\n              id\n            }\n          }\n        }\n      }\n      currentModuleEvaluations {\n        id\n        notes\n        wasPresent\n        __typename\n        ... on ClassParticipationEvaluation {\n          behaviourRating\n          skillsRating\n          collection {\n            environment {\n              code\n              label {\n                fi\n              }\n            }\n          }\n          ...EvaluationStatistics_Evaluation\n          ...EvaluationsBarChart_Evaluation\n          ...EvaluationsHistogram_Evaluation\n          ...EvaluationsAccordion_Evaluation\n        }\n        ... on DefaultEvaluation {\n          rating\n        }\n        collection {\n          id\n          date\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CollectionCreationProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        id\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n      currentModule {\n        collectionTypes {\n          id\n          name\n          category\n        }\n      }\n      ...CollectionGeneralInfoView_Group\n    }\n  }\n"): (typeof documents)["\n  query CollectionCreationProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        id\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n      currentModule {\n        collectionTypes {\n          id\n          name\n          category\n        }\n      }\n      ...CollectionGeneralInfoView_Group\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CollectionEvaluationsView_CreateCollection($createCollectionInput: CreateClassParticipationCollectionInput!, $moduleId: ID!) {\n    createClassParticipationCollection(data: $createCollectionInput, moduleId: $moduleId) {\n      ...ClassParticipationCollectionUpdate_GeneralInfoFull\n      evaluations {\n        ...ClassParticipationEvaluationUpdate_Info\n        student {\n          id\n          currentModuleEvaluations {\n            id\n          }\n        }\n      }\n      module {\n        ...CollectionModuleCacheUpdate\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CollectionEvaluationsView_CreateCollection($createCollectionInput: CreateClassParticipationCollectionInput!, $moduleId: ID!) {\n    createClassParticipationCollection(data: $createCollectionInput, moduleId: $moduleId) {\n      ...ClassParticipationCollectionUpdate_GeneralInfoFull\n      evaluations {\n        ...ClassParticipationEvaluationUpdate_Info\n        student {\n          id\n          currentModuleEvaluations {\n            id\n          }\n        }\n      }\n      module {\n        ...CollectionModuleCacheUpdate\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment CollectionGeneralInfoView_Group on Group {\n    subject {\n      code\n    }\n    currentModule {\n      id\n      info {\n        educationLevel\n        learningObjectiveGroupKey\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment CollectionGeneralInfoView_Group on Group {\n    subject {\n      code\n    }\n    currentModule {\n      id\n      info {\n        educationLevel\n        learningObjectiveGroupKey\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment CollectionParticipationsView_Group on Group {\n    students {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  fragment CollectionParticipationsView_Group on Group {\n    students {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateGroupPage_CreateGroup($input: CreateGroupInput!) {\n    createGroup(data: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation CreateGroupPage_CreateGroup($input: CreateGroupInput!) {\n    createGroup(data: $input) {\n      id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation EditTypeWeightsView_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      ...GroupCollectionTypesUpdate\n    }\n  }\n"): (typeof documents)["\n  mutation EditTypeWeightsView_UpdateGroup($id: ID!, $input: UpdateGroupInput!) {\n    updateGroup(groupId: $id, data: $input) {\n      ...GroupCollectionTypesUpdate\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query UpdateTypesProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        collectionTypes {\n          id\n          category\n          name\n          weight\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query UpdateTypesProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        collectionTypes {\n          id\n          category\n          name\n          weight\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DefaultCollectionCreationProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        id\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n      currentModule {\n        collectionTypes {\n          id\n          name\n          category\n        }\n      }\n      ...CollectionGeneralInfoView_Group\n    }\n  }\n"): (typeof documents)["\n  query DefaultCollectionCreationProvider_GetGroup($groupId: ID!) {\n    getGroup(id: $groupId) {\n      id\n      currentModule {\n        id\n        students {\n          id\n          name\n          currentModuleEvaluations {\n            id\n            notes\n          }\n        }\n      }\n      currentModule {\n        collectionTypes {\n          id\n          name\n          category\n        }\n      }\n      ...CollectionGeneralInfoView_Group\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DefaultCollectionEvaluationsView_CreateCollection($createCollectionInput: CreateDefaultCollectionInput!, $moduleId: ID!) {\n    createDefaultCollection(data: $createCollectionInput, moduleId: $moduleId) {\n      ...DefaultCollectionUpdate_Info\n      evaluations {\n        ...DefaultEvaluationUpdate_Info\n        student {\n          id\n          currentModuleEvaluations {\n            id\n          }\n        }\n      }\n      module {\n        ...CollectionModuleCacheUpdate\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DefaultCollectionEvaluationsView_CreateCollection($createCollectionInput: CreateDefaultCollectionInput!, $moduleId: ID!) {\n    createDefaultCollection(data: $createCollectionInput, moduleId: $moduleId) {\n      ...DefaultCollectionUpdate_Info\n      evaluations {\n        ...DefaultEvaluationUpdate_Info\n        student {\n          id\n          currentModuleEvaluations {\n            id\n          }\n        }\n      }\n      module {\n        ...CollectionModuleCacheUpdate\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;