#!/bin/sh

touch .env
{
  printf "NEXT_PUBLIC_BASE_URL=%sNEXT_PUBLIC_GRAPHQL_API_URL=%sNEXTAUTH_URL=%sIS_HTTPS=%s" "$NEXT_PUBLIC_BASE_URL" "$NEXT_PUBLIC_GRAPHQL_API_URL" "$NEXTAUTH_URL" "$IS_HTTPS"
} >> .env
