name: Backup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Vars
        id: get_vars
        run: |
          echo "::set-output name=date::$(date)"
          echo "::set-output name=ts::$(date +%s)"
      - run: sleep 2
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: ${{ secrets.DATABASE_URL }}
          path: "backups/backup.sql"
          options: "-O"
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "backups"
          author_name: Ekku Sipilä
          author_email: ekku.eki@gmail.com
          commit: --allow-empty
          default_author: github_actions
          message: "Backup ${{ steps.get_vars.outputs.date }}"
          tag: "bk-${{steps.get_vars.outputs.ts}}"