name: Build and push web Docker image

on:
  push:
    branches:
      - 'main'
      - 'v*'
    paths:
      - 'web/**'
      - 'Dockerfile.web'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: ekkusi/arwi-web:${{ steps.extract_branch.outputs.branch == 'main' && 'latest' || steps.extract_branch.outputs.branch }}
          platforms: linux/amd64
          secrets: |
            "GRIDLY_API_KEY=${{ secrets.GRIDLY_API_KEY }}"
            "GRIDLY_VIEW_ID=${{ secrets.GRIDLY_WEB_VIEW_ID }}"
            "BACKEND_URL=${{ steps.extract_branch.outputs.branch == 'main' && 'https://api.arwi.fi' || 'https://staging-api.arwi.fi' }}"