name: Build and push Docker image

on:
  push:
    branches:
      - 'main'


jobs:
  google-deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Check db url'
      run: echo ${{secrets.TEST_DATABASE_URL}} | sed 's/./& /g'
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/264096740042/locations/global/workloadIdentityPools/arwi-pool/providers/arwi-provider'
        service_account: 'arwi-test@appspot.gserviceaccount.com'
        project_id: 'arwi-test'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        project_id: 'arwi-test'
        build_env_vars: |-
          DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
        env_vars: |-
          DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
  # tests:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   defaults: 
  #     run:
  #       working-directory: backend
  #   services:
  #     postgres:
  #       image: postgres:15
  #       env:
  #         POSTGRES_USER: user
  #         POSTGRES_PASSWORD: password
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         # Maps tcp port 5432 on service container to the host
  #         - 5432:5432
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: 'Create .env.test file'
  #       run: |
  #         touch .env.test
  #         echo DATABASE_URL=postgresql://user:password@localhost:5432/arwi-test >> .env.test
  #         cat .env.test
  #     - name: 'Copy yarn lockfile from root'
  #       working-directory: .
  #       run: cp yarn.lock ./backend/yarn.lock
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Run tests
  #       run: yarn test-with-setup
  docker:
    # needs: tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ekkusi/arwi-backend:latest
          platforms: linux/amd64