name: Build and push backend to Google Cloud

on:
  push:
    branches:
      - 'v*'


jobs:
  google-deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/264096740042/locations/global/workloadIdentityPools/arwi-pool/providers/arwi-provider'
        service_account: 'arwi-test@appspot.gserviceaccount.com'
        project_id: 'arwi-test'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        project_id: 'arwi-test'
        build_env_vars: |-
          DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION=${{ secrets.OPENAI_ORGANIZATION }}
          NO_REDIS_SESSION=true
          NODE_ENV=test
        env_vars: |-
          DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION=${{ secrets.OPENAI_ORGANIZATION }}
          NO_REDIS_SESSION=true
          NODE_ENV=test