name: Run tests callable workflow
on:
  workflow_call:

jobs:
  run-tests-call:
    name: Run tests
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Create .env.test file'
        run: |
          touch .env.test
          echo DATABASE_URL=postgresql://user:password@localhost:5432/arwi-test >> .env.test
          echo NO_REDIS_SESSION=true >> .env.test
          cat .env.test
      - name: 'Copy yarn lockfile from root'
        working-directory: .
        run: cp yarn.lock ./backend/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test-with-setup